version: '2'

services:
  tomcat:
    image: tomcat:8.0
    ports:
      - "80:8080"
    volumes:
      - ./target/BackupHandler.war:/usr/local/tomcat/webapps/BackupHandler.war
      - ./conf/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml